### ISSUE TITLE
Add Interactivity to Contact Us Page and Footer Links

### ISSUE THREAD

**Issue by Meekunn** [balotofi/toweringheights-frontend#21]
### Description

Add Interactivity to Phone Numbers, Email Addresses, and Physical Addresses on the Footer Section and Contact Us Page.

### Tasks To Be Done 
- [ ] *Clickable phone number to call the number.*
- [ ] *Clickable email to send email to address.*
- [ ] *Clickable address linked to Google Maps.*

### Who wants to work on this issue?
I want to work on this issue. @balotofi, Kindly assign me.
