### ISSUE TITLE
Spelling and content errors

### ISSUE THREAD

**Issue by Meekunn** [balotofi/toweringheights-frontend#23]
### Description
Spelling and content errors on the website

### Tasks To Be Done
- [ ] There is an ‘individuals’ spelling error on the welcome section of the home page. 
- [ ] School timetable in about us page, Friday ending time is 2 pm, not 5 pm.
- [ ] Add first-five pic after the last descriptive paragraph on the about us page.
-
### Who wants to work on this issue?
I want to work on this issue. @balotofi, Kindly assign me.

**Comment by MehrotrajiWebsiting** [comment]
I want to work on this issue. @balotofi, Kindly assign me.
