### ISSUE TITLE
Edit README.md file

### ISSUE THREAD

**Issue by Meekunn** [balotofi/toweringheights-frontend#28]
### Description
Edit contents in the README.md file

### Tasks To Be Done
- [ ] Add the school website URL.
- [ ] Edit Contributors Section.
- [ ] Edit Contributing Section.

### Who wants to work on this issue?
I want to work on this issue. @balotofi, Kindly assign me.
